// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"auth/internal/infrastructure/model"
)

func newClient(db *gorm.DB, opts ...gen.DOOption) client {
	_client := client{}

	_client.clientDo.UseDB(db, opts...)
	_client.clientDo.UseModel(&model.Client{})

	tableName := _client.clientDo.TableName()
	_client.ALL = field.NewAsterisk(tableName)
	_client.ID = field.NewString(tableName, "id")
	_client.EncryptedSecret = field.NewString(tableName, "encrypted_secret")
	_client.UserID = field.NewInt64(tableName, "user_id")
	_client.Name = field.NewString(tableName, "name")
	_client.CreatedAt = field.NewTime(tableName, "created_at")
	_client.UpdatedAt = field.NewTime(tableName, "updated_at")

	_client.fillFieldMap()

	return _client
}

type client struct {
	clientDo

	ALL             field.Asterisk
	ID              field.String
	EncryptedSecret field.String
	UserID          field.Int64
	Name            field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (c client) Table(newTableName string) *client {
	c.clientDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c client) As(alias string) *client {
	c.clientDo.DO = *(c.clientDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *client) updateTableName(table string) *client {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.EncryptedSecret = field.NewString(table, "encrypted_secret")
	c.UserID = field.NewInt64(table, "user_id")
	c.Name = field.NewString(table, "name")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *client) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *client) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["encrypted_secret"] = c.EncryptedSecret
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["name"] = c.Name
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c client) clone(db *gorm.DB) client {
	c.clientDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c client) replaceDB(db *gorm.DB) client {
	c.clientDo.ReplaceDB(db)
	return c
}

type clientDo struct{ gen.DO }

type IClientDo interface {
	gen.SubQuery
	Debug() IClientDo
	WithContext(ctx context.Context) IClientDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IClientDo
	WriteDB() IClientDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IClientDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IClientDo
	Not(conds ...gen.Condition) IClientDo
	Or(conds ...gen.Condition) IClientDo
	Select(conds ...field.Expr) IClientDo
	Where(conds ...gen.Condition) IClientDo
	Order(conds ...field.Expr) IClientDo
	Distinct(cols ...field.Expr) IClientDo
	Omit(cols ...field.Expr) IClientDo
	Join(table schema.Tabler, on ...field.Expr) IClientDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IClientDo
	RightJoin(table schema.Tabler, on ...field.Expr) IClientDo
	Group(cols ...field.Expr) IClientDo
	Having(conds ...gen.Condition) IClientDo
	Limit(limit int) IClientDo
	Offset(offset int) IClientDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IClientDo
	Unscoped() IClientDo
	Create(values ...*model.Client) error
	CreateInBatches(values []*model.Client, batchSize int) error
	Save(values ...*model.Client) error
	First() (*model.Client, error)
	Take() (*model.Client, error)
	Last() (*model.Client, error)
	Find() ([]*model.Client, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Client, err error)
	FindInBatches(result *[]*model.Client, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Client) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IClientDo
	Assign(attrs ...field.AssignExpr) IClientDo
	Joins(fields ...field.RelationField) IClientDo
	Preload(fields ...field.RelationField) IClientDo
	FirstOrInit() (*model.Client, error)
	FirstOrCreate() (*model.Client, error)
	FindByPage(offset int, limit int) (result []*model.Client, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IClientDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c clientDo) Debug() IClientDo {
	return c.withDO(c.DO.Debug())
}

func (c clientDo) WithContext(ctx context.Context) IClientDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c clientDo) ReadDB() IClientDo {
	return c.Clauses(dbresolver.Read)
}

func (c clientDo) WriteDB() IClientDo {
	return c.Clauses(dbresolver.Write)
}

func (c clientDo) Session(config *gorm.Session) IClientDo {
	return c.withDO(c.DO.Session(config))
}

func (c clientDo) Clauses(conds ...clause.Expression) IClientDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c clientDo) Returning(value interface{}, columns ...string) IClientDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c clientDo) Not(conds ...gen.Condition) IClientDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c clientDo) Or(conds ...gen.Condition) IClientDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c clientDo) Select(conds ...field.Expr) IClientDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c clientDo) Where(conds ...gen.Condition) IClientDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c clientDo) Order(conds ...field.Expr) IClientDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c clientDo) Distinct(cols ...field.Expr) IClientDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c clientDo) Omit(cols ...field.Expr) IClientDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c clientDo) Join(table schema.Tabler, on ...field.Expr) IClientDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c clientDo) LeftJoin(table schema.Tabler, on ...field.Expr) IClientDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c clientDo) RightJoin(table schema.Tabler, on ...field.Expr) IClientDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c clientDo) Group(cols ...field.Expr) IClientDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c clientDo) Having(conds ...gen.Condition) IClientDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c clientDo) Limit(limit int) IClientDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c clientDo) Offset(offset int) IClientDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c clientDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IClientDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c clientDo) Unscoped() IClientDo {
	return c.withDO(c.DO.Unscoped())
}

func (c clientDo) Create(values ...*model.Client) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c clientDo) CreateInBatches(values []*model.Client, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c clientDo) Save(values ...*model.Client) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c clientDo) First() (*model.Client, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Client), nil
	}
}

func (c clientDo) Take() (*model.Client, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Client), nil
	}
}

func (c clientDo) Last() (*model.Client, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Client), nil
	}
}

func (c clientDo) Find() ([]*model.Client, error) {
	result, err := c.DO.Find()
	return result.([]*model.Client), err
}

func (c clientDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Client, err error) {
	buf := make([]*model.Client, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c clientDo) FindInBatches(result *[]*model.Client, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c clientDo) Attrs(attrs ...field.AssignExpr) IClientDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c clientDo) Assign(attrs ...field.AssignExpr) IClientDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c clientDo) Joins(fields ...field.RelationField) IClientDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c clientDo) Preload(fields ...field.RelationField) IClientDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c clientDo) FirstOrInit() (*model.Client, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Client), nil
	}
}

func (c clientDo) FirstOrCreate() (*model.Client, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Client), nil
	}
}

func (c clientDo) FindByPage(offset int, limit int) (result []*model.Client, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c clientDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c clientDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c clientDo) Delete(models ...*model.Client) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *clientDo) withDO(do gen.Dao) *clientDo {
	c.DO = *do.(*gen.DO)
	return c
}
