version: "3"

tasks:
  install:
    desc: "Install dependencies"
    cmds:
      - task install:aqua
      - task migrate
      - task install:backend
      - task install:frontend
      - task install:spec
      - task install:example
      - task generate
  install:aqua:
    desc: "Install aqua"
    cmds:
      - aqua i
  install:backend:
    desc: "Install backend dependencies"
    cmds:
      - go mod download
  install:frontend:
    desc: "Install frontend dependencies"
    cmds:
      - cd frontend && pnpm install
  install:spec:
    desc: "Install spec dependencies"
    cmds:
      - cd spec && pnpm install
  install:example:
    desc: "Install example dependencies"
    cmds:
      - cd example && pnpm install
  generate:
    desc: "Generate codes"
    cmds:
      - task migrate:create
      - cd spec && pnpm compile
      - go generate ./...
      - cd frontend && pnpm codegen

  migrate:create:
    cmds:
      - cd atlas && atlas migrate diff {{.CLI_ARGS}} --env local
  migrate:remove:
    cmds:
      - cd atlas && atlas migrate rm --env local

  migrate:
    desc: "Migrate database"
    cmds:
      - cd atlas && atlas migrate apply --env local
      - cd atlas && atlas migrate apply --env test
  migrate:down:
    desc: "Down migrate database"
    cmds:
      - cd atlas && atlas migrate down --env local
      - cd atlas && atlas migrate down --env test

  dev:
    desc: "Run development server"
    deps:
      - task: dev:backend
      - task: dev:frontend
      - task: dev:spec
      - task: dev:example

  dev:backend:
    desc: "Run development server for backend"
    cmds:
      - go run cmd/main.go

  dev:frontend:
    desc: "Run development server for frontend"
    cmds:
      - cd frontend && pnpm dev
  
  dev:example:
    desc: "Run development server for example"
    cmds:
      - cd example && pnpm dev

  dev:spec:
    desc: "Run development server for spec"
    deps:
      - task: dev:spec:dev
      - task: dev:spec:doc
  dev:spec:dev:
    desc: "Watch compile for spec"
    cmds:
      - cd spec && pnpm dev
  dev:spec:doc:
    desc: "API doc server for spec"
    cmds:
      - cd spec && pnpm doc

  test:
    desc: "Run test"
    cmds:
      - task test:backend
  test:
    desc: "Run test for backend"
    cmds:
      - go test ./...
