openapi: 3.0.0
info:
  title: Auth
  version: 0.0.0
tags: []
paths:
  /api/v1/account/clients/:
    get:
      operationId: Clients_listClients
      summary: Get all clients
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  clients:
                    type: array
                    items:
                      $ref: '#/components/schemas/Client'
                required:
                  - clients
    post:
      operationId: Clients_createClient
      summary: Create a new client
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/Client'
                required:
                  - client
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/ClientCreate'
              required:
                - client
  /api/v1/account/clients/:id/{id}:
    post:
      operationId: Clients_updateClient
      summary: Update a client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/Client'
                required:
                  - client
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/ClientCreate'
              required:
                - client
    delete:
      operationId: Clients_deleteClient
      summary: Delete a client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
  /api/v1/authorize:
    get:
      operationId: V1_authorize
      summary: Authorization Request
      parameters:
        - name: response_type
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: client_id
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: redirect_uri
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: scope
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: state
          in: query
          required: false
          schema:
            type: string
          explode: false
      responses:
        '302':
          description: Redirection
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: integer
                    format: int32
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
  /api/v1/login:
    post:
      operationId: V1_login
      summary: Login
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
              required:
                - name
                - password
  /api/v1/token/:
    post:
      operationId: Token_getToken
      summary: Get a token
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
              required:
                - client_id
                - client_secret
components:
  schemas:
    Client:
      type: object
      required:
        - id
        - name
        - redirect_urls
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        redirect_urls:
          type: array
          items:
            type: string
    ClientCreate:
      type: object
      required:
        - name
        - redirect_urls
      properties:
        name:
          type: string
        redirect_urls:
          type: array
          items:
            type: string
