openapi: 3.0.0
info:
  title: Auth
  version: 0.0.0
tags: []
paths:
  /account/approvals:
    post:
      operationId: ApprovalsInterface_approve
      summary: Approve a auth request
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approvals.Res4xx'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approvals.Res4xx'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Approvals.ApproveReq'
  /account/clients/:
    get:
      operationId: ClientInterface_listClients
      summary: Get all clients
      parameters:
        - name: cookie
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  clients:
                    type: array
                    items:
                      $ref: '#/components/schemas/Client'
                required:
                  - clients
    post:
      operationId: ClientInterface_createClient
      summary: Create a new client
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/Client'
                required:
                  - client
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/ClientCreate'
              required:
                - client
  /account/clients/:id/{id}:
    post:
      operationId: ClientInterface_updateClient
      summary: Update a client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/Client'
                required:
                  - client
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/ClientCreate'
              required:
                - client
    delete:
      operationId: ClientInterface_deleteClient
      summary: Delete a client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
  /authorize:
    get:
      operationId: authorize
      summary: Authorization Request
      parameters:
        - name: response_type
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: client_id
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: redirect_uri
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: scope
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: state
          in: query
          required: false
          schema:
            type: string
          explode: false
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '302':
          description: Redirection
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
    post:
      operationId: postAuthorize
      summary: Authorization Request
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '302':
          description: Redirection
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                response_type:
                  type: string
                client_id:
                  type: string
                redirect_uri:
                  type: string
                scope:
                  type: string
                state:
                  type: string
              required:
                - response_type
                - client_id
                - redirect_uri
                - scope
  /me:
    get:
      operationId: me
      summary: Get me
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                required:
                  - user
  /session:
    post:
      operationId: login
      summary: Login
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqLogin'
    delete:
      operationId: logout
      summary: Logout
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
  /signup:
    post:
      operationId: signup
      summary: Signup
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
  /token/:
    post:
      operationId: Token_getToken
      summary: Get a token
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: integer
                    format: int32
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
              required:
                - client_id
                - client_secret
components:
  schemas:
    Approvals.ApproveReq:
      type: object
      required:
        - client_id
        - scope
      properties:
        client_id:
          type: string
        scope:
          type: string
    Approvals.Res4xx:
      type: object
      required:
        - error
        - error_description
      properties:
        error:
          type: string
        error_description:
          type: string
    Client:
      type: object
      required:
        - id
        - name
        - redirect_urls
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        redirect_urls:
          type: array
          items:
            type: string
    ClientCreate:
      type: object
      required:
        - name
        - redirect_urls
      properties:
        name:
          type: string
        redirect_urls:
          type: array
          items:
            type: string
    ReqLogin:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string
    ReqSignup:
      type: object
      required:
        - name
        - password
        - password_confirmation
      properties:
        name:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    UserCreate:
      type: object
      required:
        - name
        - password
        - password_confirmation
      properties:
        name:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
servers:
  - url: https://auth.piny940.com/api/v1
    description: Auth Server
    variables: {}
