openapi: 3.0.0
info:
  title: Auth
  version: 0.0.0
tags: []
paths:
  /account/approvals:
    post:
      operationId: ApprovalsInterface_approve
      summary: Approve a auth request
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approvals.Res4xx'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approvals.Res4xx'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Approvals.ApproveReq'
  /account/clients/:
    get:
      operationId: ClientInterface_listClients
      summary: Get all clients
      parameters:
        - name: cookie
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  clients:
                    type: array
                    items:
                      $ref: '#/components/schemas/Client'
                required:
                  - clients
    post:
      operationId: ClientInterface_createClient
      summary: Create a new client
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/Client'
                required:
                  - client
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/ClientCreate'
              required:
                - client
  /account/clients/:id/{id}:
    post:
      operationId: ClientInterface_updateClient
      summary: Update a client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/Client'
                required:
                  - client
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/ClientCreate'
              required:
                - client
    delete:
      operationId: ClientInterface_deleteClient
      summary: Delete a client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
  /oauth/authorize:
    get:
      operationId: OAuthInterface_authorize
      summary: Authorization Request
      parameters:
        - name: query
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/OAuth.AuthorizeReq'
          explode: false
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '302':
          description: Redirection
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/OAuth.AuthorizeErr'
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/OAuth.AuthorizeErr'
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
    post:
      operationId: OAuthInterface_postAuthorize
      summary: Authorization Request
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '302':
          description: Redirection
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/OAuth.AuthorizeErr'
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/OAuth.AuthorizeErr'
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/OAuth.AuthorizeErr'
                  error_description:
                    type: string
                  state:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OAuth.AuthorizeReqMultiPart'
  /oauth/token:
    post:
      operationId: OAuthInterface_getToken
      summary: Get a token
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: integer
                    format: int32
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
              required:
                - client_id
                - client_secret
  /session/:
    get:
      operationId: SessionInterface_me
      summary: Get session
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session.MeRes'
    post:
      operationId: SessionInterface_login
      summary: Login
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Session.LoginErr'
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session.LoginReq'
    delete:
      operationId: SessionInterface_logout
      summary: Logout
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Session.LogoutErr'
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
  /signup:
    post:
      operationId: signup
      summary: Signup
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                required:
                  - error
                  - error_description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
components:
  schemas:
    Approvals.ApproveReq:
      type: object
      required:
        - client_id
        - scope
      properties:
        client_id:
          type: string
        scope:
          type: string
    Approvals.Res4xx:
      type: object
      required:
        - error
        - error_description
      properties:
        error:
          type: string
        error_description:
          type: string
    Client:
      type: object
      required:
        - id
        - name
        - redirect_urls
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        redirect_urls:
          type: array
          items:
            type: string
    ClientCreate:
      type: object
      required:
        - name
        - redirect_urls
      properties:
        name:
          type: string
        redirect_urls:
          type: array
          items:
            type: string
    OAuth.AuthorizeErr:
      type: string
      enum:
        - invalid_request
        - unauthorized_client
        - access_denied
        - unsupported_response_type
        - invalid_scope
        - server_error
        - temporarily_unavailable
    OAuth.AuthorizeReq:
      type: object
      required:
        - response_type
        - client_id
        - redirect_uri
        - scope
      properties:
        response_type:
          type: string
        client_id:
          type: string
        redirect_uri:
          type: string
        scope:
          type: string
        state:
          type: string
    OAuth.AuthorizeReqMultiPart:
      type: object
      required:
        - response_type
        - client_id
        - redirect_uri
        - scope
      properties:
        response_type:
          type: string
        client_id:
          type: string
        redirect_uri:
          type: string
        scope:
          type: string
        state:
          type: string
    ReqSignup:
      type: object
      required:
        - name
        - password
        - password_confirmation
      properties:
        name:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
    Session.LoginErr:
      type: string
      enum:
        - invalid_name_or_password
    Session.LoginReq:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string
    Session.LogoutErr:
      type: string
      enum:
        - not_logged_in
    Session.MeRes:
      type: object
      required:
        - user
      properties:
        user:
          type: object
          allOf:
            - $ref: '#/components/schemas/User'
          nullable: true
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    UserCreate:
      type: object
      required:
        - name
        - password
        - password_confirmation
      properties:
        name:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
servers:
  - url: https://auth.piny940.com/api/v1
    description: Auth Server
    variables: {}
