name: Setup Server
description: Setup server for testing

inputs:
  go-version:
    description: "Go version"
    required: true

runs:
  using: composite
  steps:
    - name: Copy .env.sample
      shell: bash
      run: cp .env.sample .env.test && cp .env.sample .env
    - uses: actions/cache@v5.0.2
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
        restore-keys: |
          v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
    - uses: aquaproj/aqua-installer@v4.0.4
      with:
        aqua_version: v2.43.1
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
    - run: go mod download
      shell: bash
    - uses: ariga/atlas-action/migrate/apply@v1
      with:
        dir: file://atlas/migrations
        url: postgres://postgres:postgres@localhost:5432/auth?sslmode=disable
