name: Setup Server
description: Setup server for testing

inputs:
  go-version:
    description: "Go version"
    required: true

runs:
  using: composite
  steps:
    - name: Copy .env.sample
      shell: bash
      run: cp .env.sample .env.test && cp .env.sample .env
    - uses: actions/cache@v4.2.3
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
        restore-keys: |
          v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
    - uses: aquaproj/aqua-installer@v3.1.2
      with:
        aqua_version: v2.28.0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
    - run: go mod download
      shell: bash
    - uses: ariga/setup-atlas@v0
    - uses: ariga/atlas-action/migrate/apply@v1
      with:
        dir: file://atlas/migrations
        url: postgres://postgres:postgres@localhost:5432/auth?sslmode=disable
