// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BasicAuthScopes  = "BasicAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ApprovalsApproveErr.
const (
	ApprovalsApproveErrInvalidClient ApprovalsApproveErr = "invalid_client"
	ApprovalsApproveErrInvalidScope  ApprovalsApproveErr = "invalid_scope"
)

// Defines values for ClientsGetClientErr.
const (
	ClientNotFound ClientsGetClientErr = "client_not_found"
)

// Defines values for OAuthAuthorizeErr.
const (
	OAuthAuthorizeErrAccessDenied            OAuthAuthorizeErr = "access_denied"
	OAuthAuthorizeErrInvalidRequest          OAuthAuthorizeErr = "invalid_request"
	OAuthAuthorizeErrInvalidScope            OAuthAuthorizeErr = "invalid_scope"
	OAuthAuthorizeErrServerError             OAuthAuthorizeErr = "server_error"
	OAuthAuthorizeErrTemporarilyUnavailable  OAuthAuthorizeErr = "temporarily_unavailable"
	OAuthAuthorizeErrUnauthorizedClient      OAuthAuthorizeErr = "unauthorized_client"
	OAuthAuthorizeErrUnsupportedResponseType OAuthAuthorizeErr = "unsupported_response_type"
)

// Defines values for OAuthAuthorizeResponseType.
const (
	Code OAuthAuthorizeResponseType = "code"
)

// Defines values for OAuthTokenCacheControlHeader.
const (
	OAuthTokenCacheControlHeaderNoStore OAuthTokenCacheControlHeader = "no-store"
)

// Defines values for OAuthTokenErr.
const (
	InvalidRequest OAuthTokenErr = "invalid_request"
)

// Defines values for OAuthTokenGrantType.
const (
	AuthorizationCode OAuthTokenGrantType = "authorization_code"
)

// Defines values for OAuthTokenPragmaHeader.
const (
	OAuthTokenPragmaHeaderNoStore OAuthTokenPragmaHeader = "no-store"
)

// Defines values for OAuthTokenTokenType.
const (
	Bearer OAuthTokenTokenType = "Bearer"
)

// Defines values for SessionLoginErr.
const (
	InvalidNameOrPassword SessionLoginErr = "invalid_name_or_password"
)

// Defines values for SessionLogoutErr.
const (
	NotLoggedIn SessionLogoutErr = "not_logged_in"
)

// Defines values for UsersSignupErr.
const (
	NameAlreadyUsed              UsersSignupErr = "name_already_used"
	NameLengthNotEnough          UsersSignupErr = "name_length_not_enough"
	PasswordConfirmationNotMatch UsersSignupErr = "password_confirmation_not_match"
	PasswordLengthNotEnough      UsersSignupErr = "password_length_not_enough"
)

// AccountApprovalsListApprovalsRes defines model for Account.Approvals.ListApprovalsRes.
type AccountApprovalsListApprovalsRes struct {
	Approvals []Approval `json:"approvals"`
}

// AccountClientsCreateClientReq defines model for Account.Clients.CreateClientReq.
type AccountClientsCreateClientReq struct {
	Name         string   `json:"name"`
	RedirectUrls []string `json:"redirect_urls"`
}

// AccountClientsCreatedClient defines model for Account.Clients.CreatedClient.
type AccountClientsCreatedClient struct {
	Id           string   `json:"id"`
	Name         string   `json:"name"`
	RedirectUrls []string `json:"redirect_urls"`
	Secret       string   `json:"secret"`
}

// AccountClientsUpdateClientReq defines model for Account.Clients.UpdateClientReq.
type AccountClientsUpdateClientReq struct {
	Name         string   `json:"name"`
	RedirectUrls []string `json:"redirect_urls"`
}

// Approval defines model for Approval.
type Approval struct {
	Client PublicClient `json:"client"`
	Id     string       `json:"id"`
	Scopes []string     `json:"scopes"`
}

// ApprovalsApproveErr defines model for Approvals.ApproveErr.
type ApprovalsApproveErr string

// ApprovalsApproveReq defines model for Approvals.ApproveReq.
type ApprovalsApproveReq struct {
	ClientId string `json:"client_id"`
	Scope    string `json:"scope"`
}

// Client defines model for Client.
type Client struct {
	Id           string   `json:"id"`
	Name         string   `json:"name"`
	RedirectUrls []string `json:"redirect_urls"`
}

// ClientsGetClientErr defines model for Clients.GetClientErr.
type ClientsGetClientErr string

// ClientsGetClientRes defines model for Clients.GetClientRes.
type ClientsGetClientRes struct {
	Client PublicClient `json:"client"`
}

// OAuthAuthorizeErr defines model for OAuth.AuthorizeErr.
type OAuthAuthorizeErr string

// OAuthAuthorizeReqMultiPart defines model for OAuth.AuthorizeReqMultiPart.
type OAuthAuthorizeReqMultiPart struct {
	ClientId     string                     `json:"client_id"`
	MaxAge       *int32                     `json:"max_age,omitempty"`
	RedirectUri  string                     `json:"redirect_uri"`
	ResponseType OAuthAuthorizeResponseType `json:"response_type"`
	Scope        string                     `json:"scope"`
	State        *string                    `json:"state,omitempty"`
}

// OAuthAuthorizeResponseType defines model for OAuth.AuthorizeResponseType.
type OAuthAuthorizeResponseType string

// OAuthTokenCacheControlHeader defines model for OAuth.TokenCacheControlHeader.
type OAuthTokenCacheControlHeader string

// OAuthTokenErr defines model for OAuth.TokenErr.
type OAuthTokenErr string

// OAuthTokenGrantType defines model for OAuth.TokenGrantType.
type OAuthTokenGrantType string

// OAuthTokenPragmaHeader defines model for OAuth.TokenPragmaHeader.
type OAuthTokenPragmaHeader string

// OAuthTokenReq defines model for OAuth.TokenReq.
type OAuthTokenReq struct {
	Code        string              `json:"code"`
	GrantType   OAuthTokenGrantType `json:"grant_type"`
	RedirectUri string              `json:"redirect_uri"`
}

// OAuthTokenRes defines model for OAuth.TokenRes.
type OAuthTokenRes struct {
	AccessToken string              `json:"access_token"`
	ExpiresIn   int32               `json:"expires_in"`
	IdToken     *string             `json:"id_token,omitempty"`
	TokenType   OAuthTokenTokenType `json:"token_type"`
}

// OAuthTokenTokenType defines model for OAuth.TokenTokenType.
type OAuthTokenTokenType string

// PublicClient defines model for PublicClient.
type PublicClient struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// SessionLoginErr defines model for Session.LoginErr.
type SessionLoginErr string

// SessionLoginReq defines model for Session.LoginReq.
type SessionLoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// SessionLogoutErr defines model for Session.LogoutErr.
type SessionLogoutErr string

// SessionMeRes defines model for Session.MeRes.
type SessionMeRes struct {
	User *User `json:"user"`
}

// User defines model for User.
type User struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// UserinfoUserinfoRes defines model for Userinfo.UserinfoRes.
type UserinfoUserinfoRes struct {
	Name *string `json:"name,omitempty"`
	Sub  string  `json:"sub"`
}

// UsersReqSignup defines model for Users.ReqSignup.
type UsersReqSignup struct {
	Name                 string `json:"name"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"password_confirmation"`
}

// UsersSignupErr defines model for Users.SignupErr.
type UsersSignupErr string

// AccountClientsCreateClientJSONBody defines parameters for AccountClientsCreateClient.
type AccountClientsCreateClientJSONBody struct {
	Client AccountClientsCreateClientReq `json:"client"`
}

// AccountClientsUpdateClientJSONBody defines parameters for AccountClientsUpdateClient.
type AccountClientsUpdateClientJSONBody struct {
	Client AccountClientsUpdateClientReq `json:"client"`
}

// OAuthInterfaceAuthorizeParams defines parameters for OAuthInterfaceAuthorize.
type OAuthInterfaceAuthorizeParams struct {
	ResponseType OAuthAuthorizeResponseType `form:"response_type" json:"response_type"`
	ClientId     string                     `form:"client_id" json:"client_id"`
	RedirectUri  string                     `form:"redirect_uri" json:"redirect_uri"`
	Scope        string                     `form:"scope" json:"scope"`
	State        *string                    `form:"state,omitempty" json:"state,omitempty"`
	MaxAge       *int32                     `form:"max_age,omitempty" json:"max_age,omitempty"`
}

// OAuthInterfaceGetTokenParams defines parameters for OAuthInterfaceGetToken.
type OAuthInterfaceGetTokenParams struct {
	Authorization string `json:"authorization"`
}

// ApprovalsInterfaceApproveJSONRequestBody defines body for ApprovalsInterfaceApprove for application/json ContentType.
type ApprovalsInterfaceApproveJSONRequestBody = ApprovalsApproveReq

// AccountClientsCreateClientJSONRequestBody defines body for AccountClientsCreateClient for application/json ContentType.
type AccountClientsCreateClientJSONRequestBody AccountClientsCreateClientJSONBody

// AccountClientsUpdateClientJSONRequestBody defines body for AccountClientsUpdateClient for application/json ContentType.
type AccountClientsUpdateClientJSONRequestBody AccountClientsUpdateClientJSONBody

// OAuthInterfacePostAuthorizeMultipartRequestBody defines body for OAuthInterfacePostAuthorize for multipart/form-data ContentType.
type OAuthInterfacePostAuthorizeMultipartRequestBody = OAuthAuthorizeReqMultiPart

// OAuthInterfaceGetTokenFormdataRequestBody defines body for OAuthInterfaceGetToken for application/x-www-form-urlencoded ContentType.
type OAuthInterfaceGetTokenFormdataRequestBody = OAuthTokenReq

// SessionInterfaceLoginJSONRequestBody defines body for SessionInterfaceLogin for application/json ContentType.
type SessionInterfaceLoginJSONRequestBody = SessionLoginReq

// UsersInterfaceSignupJSONRequestBody defines body for UsersInterfaceSignup for application/json ContentType.
type UsersInterfaceSignupJSONRequestBody = UsersReqSignup

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all approvals
	// (GET /account/approvals)
	ApprovalsListApprovals(ctx echo.Context) error
	// Approve a auth request
	// (POST /account/approvals)
	ApprovalsInterfaceApprove(ctx echo.Context) error
	// Delete an approval
	// (DELETE /account/approvals/{id})
	ApprovalsDeleteApproval(ctx echo.Context, id string) error
	// Get all clients
	// (GET /account/clients)
	AccountClientsListClients(ctx echo.Context) error
	// Create a new client
	// (POST /account/clients)
	AccountClientsCreateClient(ctx echo.Context) error
	// Delete a client
	// (DELETE /account/clients/{id})
	AccountClientsDeleteClient(ctx echo.Context, id string) error
	// Get a client
	// (GET /account/clients/{id})
	AccountClientsGetClient(ctx echo.Context, id string) error
	// Update a client
	// (POST /account/clients/{id})
	AccountClientsUpdateClient(ctx echo.Context, id string) error
	// Get a client
	// (GET /clients/{id})
	ClientsInterfaceGetClient(ctx echo.Context, id string) error
	// Check health
	// (GET /healthz)
	HealthzCheck(ctx echo.Context) error
	// Authorization Request
	// (GET /oauth/authorize)
	OAuthInterfaceAuthorize(ctx echo.Context, params OAuthInterfaceAuthorizeParams) error
	// Authorization Request
	// (POST /oauth/authorize)
	OAuthInterfacePostAuthorize(ctx echo.Context) error
	// Get JSON Web Key Set
	// (GET /oauth/jwks)
	OAuthInterfaceGetJwks(ctx echo.Context) error
	// Get token
	// (POST /oauth/token)
	OAuthInterfaceGetToken(ctx echo.Context, params OAuthInterfaceGetTokenParams) error
	// Logout
	// (DELETE /session)
	SessionInterfaceLogout(ctx echo.Context) error
	// Get session
	// (GET /session)
	SessionInterfaceMe(ctx echo.Context) error
	// Login
	// (POST /session)
	SessionInterfaceLogin(ctx echo.Context) error
	// Get userinfo
	// (GET /userinfo)
	UserinfoGetUserinfo(ctx echo.Context) error
	// Signup
	// (POST /users/signup)
	UsersInterfaceSignup(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ApprovalsListApprovals converts echo context to params.
func (w *ServerInterfaceWrapper) ApprovalsListApprovals(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApprovalsListApprovals(ctx)
	return err
}

// ApprovalsInterfaceApprove converts echo context to params.
func (w *ServerInterfaceWrapper) ApprovalsInterfaceApprove(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApprovalsInterfaceApprove(ctx)
	return err
}

// ApprovalsDeleteApproval converts echo context to params.
func (w *ServerInterfaceWrapper) ApprovalsDeleteApproval(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApprovalsDeleteApproval(ctx, id)
	return err
}

// AccountClientsListClients converts echo context to params.
func (w *ServerInterfaceWrapper) AccountClientsListClients(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AccountClientsListClients(ctx)
	return err
}

// AccountClientsCreateClient converts echo context to params.
func (w *ServerInterfaceWrapper) AccountClientsCreateClient(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AccountClientsCreateClient(ctx)
	return err
}

// AccountClientsDeleteClient converts echo context to params.
func (w *ServerInterfaceWrapper) AccountClientsDeleteClient(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AccountClientsDeleteClient(ctx, id)
	return err
}

// AccountClientsGetClient converts echo context to params.
func (w *ServerInterfaceWrapper) AccountClientsGetClient(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AccountClientsGetClient(ctx, id)
	return err
}

// AccountClientsUpdateClient converts echo context to params.
func (w *ServerInterfaceWrapper) AccountClientsUpdateClient(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AccountClientsUpdateClient(ctx, id)
	return err
}

// ClientsInterfaceGetClient converts echo context to params.
func (w *ServerInterfaceWrapper) ClientsInterfaceGetClient(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ClientsInterfaceGetClient(ctx, id)
	return err
}

// HealthzCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthzCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthzCheck(ctx)
	return err
}

// OAuthInterfaceAuthorize converts echo context to params.
func (w *ServerInterfaceWrapper) OAuthInterfaceAuthorize(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params OAuthInterfaceAuthorizeParams
	// ------------- Required query parameter "response_type" -------------

	err = runtime.BindQueryParameter("form", false, true, "response_type", ctx.QueryParams(), &params.ResponseType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter response_type: %s", err))
	}

	// ------------- Required query parameter "client_id" -------------

	err = runtime.BindQueryParameter("form", false, true, "client_id", ctx.QueryParams(), &params.ClientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter client_id: %s", err))
	}

	// ------------- Required query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameter("form", false, true, "redirect_uri", ctx.QueryParams(), &params.RedirectUri)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter redirect_uri: %s", err))
	}

	// ------------- Required query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", false, true, "scope", ctx.QueryParams(), &params.Scope)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter scope: %s", err))
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", false, false, "state", ctx.QueryParams(), &params.State)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// ------------- Optional query parameter "max_age" -------------

	err = runtime.BindQueryParameter("form", false, false, "max_age", ctx.QueryParams(), &params.MaxAge)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter max_age: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OAuthInterfaceAuthorize(ctx, params)
	return err
}

// OAuthInterfacePostAuthorize converts echo context to params.
func (w *ServerInterfaceWrapper) OAuthInterfacePostAuthorize(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OAuthInterfacePostAuthorize(ctx)
	return err
}

// OAuthInterfaceGetJwks converts echo context to params.
func (w *ServerInterfaceWrapper) OAuthInterfaceGetJwks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OAuthInterfaceGetJwks(ctx)
	return err
}

// OAuthInterfaceGetToken converts echo context to params.
func (w *ServerInterfaceWrapper) OAuthInterfaceGetToken(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params OAuthInterfaceGetTokenParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("authorization")]; found {
		var Authorization string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OAuthInterfaceGetToken(ctx, params)
	return err
}

// SessionInterfaceLogout converts echo context to params.
func (w *ServerInterfaceWrapper) SessionInterfaceLogout(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SessionInterfaceLogout(ctx)
	return err
}

// SessionInterfaceMe converts echo context to params.
func (w *ServerInterfaceWrapper) SessionInterfaceMe(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SessionInterfaceMe(ctx)
	return err
}

// SessionInterfaceLogin converts echo context to params.
func (w *ServerInterfaceWrapper) SessionInterfaceLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SessionInterfaceLogin(ctx)
	return err
}

// UserinfoGetUserinfo converts echo context to params.
func (w *ServerInterfaceWrapper) UserinfoGetUserinfo(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UserinfoGetUserinfo(ctx)
	return err
}

// UsersInterfaceSignup converts echo context to params.
func (w *ServerInterfaceWrapper) UsersInterfaceSignup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UsersInterfaceSignup(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/account/approvals", wrapper.ApprovalsListApprovals)
	router.POST(baseURL+"/account/approvals", wrapper.ApprovalsInterfaceApprove)
	router.DELETE(baseURL+"/account/approvals/:id", wrapper.ApprovalsDeleteApproval)
	router.GET(baseURL+"/account/clients", wrapper.AccountClientsListClients)
	router.POST(baseURL+"/account/clients", wrapper.AccountClientsCreateClient)
	router.DELETE(baseURL+"/account/clients/:id", wrapper.AccountClientsDeleteClient)
	router.GET(baseURL+"/account/clients/:id", wrapper.AccountClientsGetClient)
	router.POST(baseURL+"/account/clients/:id", wrapper.AccountClientsUpdateClient)
	router.GET(baseURL+"/clients/:id", wrapper.ClientsInterfaceGetClient)
	router.GET(baseURL+"/healthz", wrapper.HealthzCheck)
	router.GET(baseURL+"/oauth/authorize", wrapper.OAuthInterfaceAuthorize)
	router.POST(baseURL+"/oauth/authorize", wrapper.OAuthInterfacePostAuthorize)
	router.GET(baseURL+"/oauth/jwks", wrapper.OAuthInterfaceGetJwks)
	router.POST(baseURL+"/oauth/token", wrapper.OAuthInterfaceGetToken)
	router.DELETE(baseURL+"/session", wrapper.SessionInterfaceLogout)
	router.GET(baseURL+"/session", wrapper.SessionInterfaceMe)
	router.POST(baseURL+"/session", wrapper.SessionInterfaceLogin)
	router.GET(baseURL+"/userinfo", wrapper.UserinfoGetUserinfo)
	router.POST(baseURL+"/users/signup", wrapper.UsersInterfaceSignup)

}

type ApprovalsListApprovalsRequestObject struct {
}

type ApprovalsListApprovalsResponseObject interface {
	VisitApprovalsListApprovalsResponse(w http.ResponseWriter) error
}

type ApprovalsListApprovals200JSONResponse AccountApprovalsListApprovalsRes

func (response ApprovalsListApprovals200JSONResponse) VisitApprovalsListApprovalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApprovalsInterfaceApproveRequestObject struct {
	Body *ApprovalsInterfaceApproveJSONRequestBody
}

type ApprovalsInterfaceApproveResponseObject interface {
	VisitApprovalsInterfaceApproveResponse(w http.ResponseWriter) error
}

type ApprovalsInterfaceApprove204Response struct {
}

func (response ApprovalsInterfaceApprove204Response) VisitApprovalsInterfaceApproveResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ApprovalsInterfaceApprove400JSONResponse struct {
	Error            ApprovalsApproveErr `json:"error"`
	ErrorDescription string              `json:"error_description"`
}

func (response ApprovalsInterfaceApprove400JSONResponse) VisitApprovalsInterfaceApproveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApprovalsDeleteApprovalRequestObject struct {
	Id string `json:"id"`
}

type ApprovalsDeleteApprovalResponseObject interface {
	VisitApprovalsDeleteApprovalResponse(w http.ResponseWriter) error
}

type ApprovalsDeleteApproval204Response struct {
}

func (response ApprovalsDeleteApproval204Response) VisitApprovalsDeleteApprovalResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ApprovalsDeleteApproval404JSONResponse struct {
	Error string `json:"error"`
}

func (response ApprovalsDeleteApproval404JSONResponse) VisitApprovalsDeleteApprovalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AccountClientsListClientsRequestObject struct {
}

type AccountClientsListClientsResponseObject interface {
	VisitAccountClientsListClientsResponse(w http.ResponseWriter) error
}

type AccountClientsListClients200JSONResponse struct {
	Clients []Client `json:"clients"`
}

func (response AccountClientsListClients200JSONResponse) VisitAccountClientsListClientsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AccountClientsCreateClientRequestObject struct {
	Body *AccountClientsCreateClientJSONRequestBody
}

type AccountClientsCreateClientResponseObject interface {
	VisitAccountClientsCreateClientResponse(w http.ResponseWriter) error
}

type AccountClientsCreateClient201JSONResponse struct {
	Client AccountClientsCreatedClient `json:"client"`
}

func (response AccountClientsCreateClient201JSONResponse) VisitAccountClientsCreateClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AccountClientsCreateClient400JSONResponse struct {
	Error string `json:"error"`
}

func (response AccountClientsCreateClient400JSONResponse) VisitAccountClientsCreateClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AccountClientsDeleteClientRequestObject struct {
	Id string `json:"id"`
}

type AccountClientsDeleteClientResponseObject interface {
	VisitAccountClientsDeleteClientResponse(w http.ResponseWriter) error
}

type AccountClientsDeleteClient204Response struct {
}

func (response AccountClientsDeleteClient204Response) VisitAccountClientsDeleteClientResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AccountClientsDeleteClient400JSONResponse struct {
	Error string `json:"error"`
}

func (response AccountClientsDeleteClient400JSONResponse) VisitAccountClientsDeleteClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AccountClientsGetClientRequestObject struct {
	Id string `json:"id"`
}

type AccountClientsGetClientResponseObject interface {
	VisitAccountClientsGetClientResponse(w http.ResponseWriter) error
}

type AccountClientsGetClient200JSONResponse struct {
	Client Client `json:"client"`
}

func (response AccountClientsGetClient200JSONResponse) VisitAccountClientsGetClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AccountClientsGetClient404JSONResponse struct {
	Error string `json:"error"`
}

func (response AccountClientsGetClient404JSONResponse) VisitAccountClientsGetClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AccountClientsUpdateClientRequestObject struct {
	Id   string `json:"id"`
	Body *AccountClientsUpdateClientJSONRequestBody
}

type AccountClientsUpdateClientResponseObject interface {
	VisitAccountClientsUpdateClientResponse(w http.ResponseWriter) error
}

type AccountClientsUpdateClient204Response struct {
}

func (response AccountClientsUpdateClient204Response) VisitAccountClientsUpdateClientResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AccountClientsUpdateClient400JSONResponse struct {
	Error string `json:"error"`
}

func (response AccountClientsUpdateClient400JSONResponse) VisitAccountClientsUpdateClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ClientsInterfaceGetClientRequestObject struct {
	Id string `json:"id"`
}

type ClientsInterfaceGetClientResponseObject interface {
	VisitClientsInterfaceGetClientResponse(w http.ResponseWriter) error
}

type ClientsInterfaceGetClient200JSONResponse ClientsGetClientRes

func (response ClientsInterfaceGetClient200JSONResponse) VisitClientsInterfaceGetClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ClientsInterfaceGetClient400JSONResponse struct {
	Error            ClientsGetClientErr `json:"error"`
	ErrorDescription string              `json:"error_description"`
}

func (response ClientsInterfaceGetClient400JSONResponse) VisitClientsInterfaceGetClientResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HealthzCheckRequestObject struct {
}

type HealthzCheckResponseObject interface {
	VisitHealthzCheckResponse(w http.ResponseWriter) error
}

type HealthzCheck200Response struct {
}

func (response HealthzCheck200Response) VisitHealthzCheckResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type OAuthInterfaceAuthorizeRequestObject struct {
	Params OAuthInterfaceAuthorizeParams
}

type OAuthInterfaceAuthorizeResponseObject interface {
	VisitOAuthInterfaceAuthorizeResponse(w http.ResponseWriter) error
}

type OAuthInterfaceAuthorize204Response struct {
}

func (response OAuthInterfaceAuthorize204Response) VisitOAuthInterfaceAuthorizeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OAuthInterfaceAuthorize302ResponseHeaders struct {
	Location string
}

type OAuthInterfaceAuthorize302Response struct {
	Headers OAuthInterfaceAuthorize302ResponseHeaders
}

func (response OAuthInterfaceAuthorize302Response) VisitOAuthInterfaceAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type OAuthInterfaceAuthorize400JSONResponse struct {
	Error            OAuthAuthorizeErr `json:"error"`
	ErrorDescription string            `json:"error_description"`
	State            *string           `json:"state,omitempty"`
}

func (response OAuthInterfaceAuthorize400JSONResponse) VisitOAuthInterfaceAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type OAuthInterfacePostAuthorizeRequestObject struct {
	Body *multipart.Reader
}

type OAuthInterfacePostAuthorizeResponseObject interface {
	VisitOAuthInterfacePostAuthorizeResponse(w http.ResponseWriter) error
}

type OAuthInterfacePostAuthorize204Response struct {
}

func (response OAuthInterfacePostAuthorize204Response) VisitOAuthInterfacePostAuthorizeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OAuthInterfacePostAuthorize302ResponseHeaders struct {
	Location string
}

type OAuthInterfacePostAuthorize302Response struct {
	Headers OAuthInterfacePostAuthorize302ResponseHeaders
}

func (response OAuthInterfacePostAuthorize302Response) VisitOAuthInterfacePostAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type OAuthInterfacePostAuthorize400JSONResponse struct {
	Error            OAuthAuthorizeErr `json:"error"`
	ErrorDescription string            `json:"error_description"`
	State            *string           `json:"state,omitempty"`
}

func (response OAuthInterfacePostAuthorize400JSONResponse) VisitOAuthInterfacePostAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type OAuthInterfaceGetJwksRequestObject struct {
}

type OAuthInterfaceGetJwksResponseObject interface {
	VisitOAuthInterfaceGetJwksResponse(w http.ResponseWriter) error
}

type OAuthInterfaceGetJwks200JSONResponse map[string]interface{}

func (response OAuthInterfaceGetJwks200JSONResponse) VisitOAuthInterfaceGetJwksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type OAuthInterfaceGetTokenRequestObject struct {
	Params OAuthInterfaceGetTokenParams
	Body   *OAuthInterfaceGetTokenFormdataRequestBody
}

type OAuthInterfaceGetTokenResponseObject interface {
	VisitOAuthInterfaceGetTokenResponse(w http.ResponseWriter) error
}

type OAuthInterfaceGetToken200ResponseHeaders struct {
	CacheControl OAuthTokenCacheControlHeader
	Pragma       OAuthTokenPragmaHeader
}

type OAuthInterfaceGetToken200JSONResponse struct {
	Body    OAuthTokenRes
	Headers OAuthInterfaceGetToken200ResponseHeaders
}

func (response OAuthInterfaceGetToken200JSONResponse) VisitOAuthInterfaceGetTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("cache-control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("pragma", fmt.Sprint(response.Headers.Pragma))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type OAuthInterfaceGetToken400JSONResponse struct {
	Error            OAuthTokenErr `json:"error"`
	ErrorDescription string        `json:"error_description"`
}

func (response OAuthInterfaceGetToken400JSONResponse) VisitOAuthInterfaceGetTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SessionInterfaceLogoutRequestObject struct {
}

type SessionInterfaceLogoutResponseObject interface {
	VisitSessionInterfaceLogoutResponse(w http.ResponseWriter) error
}

type SessionInterfaceLogout204Response struct {
}

func (response SessionInterfaceLogout204Response) VisitSessionInterfaceLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SessionInterfaceMeRequestObject struct {
}

type SessionInterfaceMeResponseObject interface {
	VisitSessionInterfaceMeResponse(w http.ResponseWriter) error
}

type SessionInterfaceMe200JSONResponse SessionMeRes

func (response SessionInterfaceMe200JSONResponse) VisitSessionInterfaceMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SessionInterfaceLoginRequestObject struct {
	Body *SessionInterfaceLoginJSONRequestBody
}

type SessionInterfaceLoginResponseObject interface {
	VisitSessionInterfaceLoginResponse(w http.ResponseWriter) error
}

type SessionInterfaceLogin204Response struct {
}

func (response SessionInterfaceLogin204Response) VisitSessionInterfaceLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SessionInterfaceLogin400JSONResponse struct {
	Error            SessionLoginErr `json:"error"`
	ErrorDescription string          `json:"error_description"`
}

func (response SessionInterfaceLogin400JSONResponse) VisitSessionInterfaceLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UserinfoGetUserinfoRequestObject struct {
}

type UserinfoGetUserinfoResponseObject interface {
	VisitUserinfoGetUserinfoResponse(w http.ResponseWriter) error
}

type UserinfoGetUserinfo200JSONResponse UserinfoUserinfoRes

func (response UserinfoGetUserinfo200JSONResponse) VisitUserinfoGetUserinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UsersInterfaceSignupRequestObject struct {
	Body *UsersInterfaceSignupJSONRequestBody
}

type UsersInterfaceSignupResponseObject interface {
	VisitUsersInterfaceSignupResponse(w http.ResponseWriter) error
}

type UsersInterfaceSignup204ResponseHeaders struct {
	SetCookie string
}

type UsersInterfaceSignup204Response struct {
	Headers UsersInterfaceSignup204ResponseHeaders
}

func (response UsersInterfaceSignup204Response) VisitUsersInterfaceSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("set-cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type UsersInterfaceSignup400JSONResponse struct {
	Error            UsersSignupErr `json:"error"`
	ErrorDescription string         `json:"error_description"`
}

func (response UsersInterfaceSignup400JSONResponse) VisitUsersInterfaceSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all approvals
	// (GET /account/approvals)
	ApprovalsListApprovals(ctx context.Context, request ApprovalsListApprovalsRequestObject) (ApprovalsListApprovalsResponseObject, error)
	// Approve a auth request
	// (POST /account/approvals)
	ApprovalsInterfaceApprove(ctx context.Context, request ApprovalsInterfaceApproveRequestObject) (ApprovalsInterfaceApproveResponseObject, error)
	// Delete an approval
	// (DELETE /account/approvals/{id})
	ApprovalsDeleteApproval(ctx context.Context, request ApprovalsDeleteApprovalRequestObject) (ApprovalsDeleteApprovalResponseObject, error)
	// Get all clients
	// (GET /account/clients)
	AccountClientsListClients(ctx context.Context, request AccountClientsListClientsRequestObject) (AccountClientsListClientsResponseObject, error)
	// Create a new client
	// (POST /account/clients)
	AccountClientsCreateClient(ctx context.Context, request AccountClientsCreateClientRequestObject) (AccountClientsCreateClientResponseObject, error)
	// Delete a client
	// (DELETE /account/clients/{id})
	AccountClientsDeleteClient(ctx context.Context, request AccountClientsDeleteClientRequestObject) (AccountClientsDeleteClientResponseObject, error)
	// Get a client
	// (GET /account/clients/{id})
	AccountClientsGetClient(ctx context.Context, request AccountClientsGetClientRequestObject) (AccountClientsGetClientResponseObject, error)
	// Update a client
	// (POST /account/clients/{id})
	AccountClientsUpdateClient(ctx context.Context, request AccountClientsUpdateClientRequestObject) (AccountClientsUpdateClientResponseObject, error)
	// Get a client
	// (GET /clients/{id})
	ClientsInterfaceGetClient(ctx context.Context, request ClientsInterfaceGetClientRequestObject) (ClientsInterfaceGetClientResponseObject, error)
	// Check health
	// (GET /healthz)
	HealthzCheck(ctx context.Context, request HealthzCheckRequestObject) (HealthzCheckResponseObject, error)
	// Authorization Request
	// (GET /oauth/authorize)
	OAuthInterfaceAuthorize(ctx context.Context, request OAuthInterfaceAuthorizeRequestObject) (OAuthInterfaceAuthorizeResponseObject, error)
	// Authorization Request
	// (POST /oauth/authorize)
	OAuthInterfacePostAuthorize(ctx context.Context, request OAuthInterfacePostAuthorizeRequestObject) (OAuthInterfacePostAuthorizeResponseObject, error)
	// Get JSON Web Key Set
	// (GET /oauth/jwks)
	OAuthInterfaceGetJwks(ctx context.Context, request OAuthInterfaceGetJwksRequestObject) (OAuthInterfaceGetJwksResponseObject, error)
	// Get token
	// (POST /oauth/token)
	OAuthInterfaceGetToken(ctx context.Context, request OAuthInterfaceGetTokenRequestObject) (OAuthInterfaceGetTokenResponseObject, error)
	// Logout
	// (DELETE /session)
	SessionInterfaceLogout(ctx context.Context, request SessionInterfaceLogoutRequestObject) (SessionInterfaceLogoutResponseObject, error)
	// Get session
	// (GET /session)
	SessionInterfaceMe(ctx context.Context, request SessionInterfaceMeRequestObject) (SessionInterfaceMeResponseObject, error)
	// Login
	// (POST /session)
	SessionInterfaceLogin(ctx context.Context, request SessionInterfaceLoginRequestObject) (SessionInterfaceLoginResponseObject, error)
	// Get userinfo
	// (GET /userinfo)
	UserinfoGetUserinfo(ctx context.Context, request UserinfoGetUserinfoRequestObject) (UserinfoGetUserinfoResponseObject, error)
	// Signup
	// (POST /users/signup)
	UsersInterfaceSignup(ctx context.Context, request UsersInterfaceSignupRequestObject) (UsersInterfaceSignupResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ApprovalsListApprovals operation middleware
func (sh *strictHandler) ApprovalsListApprovals(ctx echo.Context) error {
	var request ApprovalsListApprovalsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApprovalsListApprovals(ctx.Request().Context(), request.(ApprovalsListApprovalsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApprovalsListApprovals")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ApprovalsListApprovalsResponseObject); ok {
		return validResponse.VisitApprovalsListApprovalsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ApprovalsInterfaceApprove operation middleware
func (sh *strictHandler) ApprovalsInterfaceApprove(ctx echo.Context) error {
	var request ApprovalsInterfaceApproveRequestObject

	var body ApprovalsInterfaceApproveJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApprovalsInterfaceApprove(ctx.Request().Context(), request.(ApprovalsInterfaceApproveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApprovalsInterfaceApprove")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ApprovalsInterfaceApproveResponseObject); ok {
		return validResponse.VisitApprovalsInterfaceApproveResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ApprovalsDeleteApproval operation middleware
func (sh *strictHandler) ApprovalsDeleteApproval(ctx echo.Context, id string) error {
	var request ApprovalsDeleteApprovalRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApprovalsDeleteApproval(ctx.Request().Context(), request.(ApprovalsDeleteApprovalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApprovalsDeleteApproval")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ApprovalsDeleteApprovalResponseObject); ok {
		return validResponse.VisitApprovalsDeleteApprovalResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AccountClientsListClients operation middleware
func (sh *strictHandler) AccountClientsListClients(ctx echo.Context) error {
	var request AccountClientsListClientsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AccountClientsListClients(ctx.Request().Context(), request.(AccountClientsListClientsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AccountClientsListClients")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AccountClientsListClientsResponseObject); ok {
		return validResponse.VisitAccountClientsListClientsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AccountClientsCreateClient operation middleware
func (sh *strictHandler) AccountClientsCreateClient(ctx echo.Context) error {
	var request AccountClientsCreateClientRequestObject

	var body AccountClientsCreateClientJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AccountClientsCreateClient(ctx.Request().Context(), request.(AccountClientsCreateClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AccountClientsCreateClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AccountClientsCreateClientResponseObject); ok {
		return validResponse.VisitAccountClientsCreateClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AccountClientsDeleteClient operation middleware
func (sh *strictHandler) AccountClientsDeleteClient(ctx echo.Context, id string) error {
	var request AccountClientsDeleteClientRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AccountClientsDeleteClient(ctx.Request().Context(), request.(AccountClientsDeleteClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AccountClientsDeleteClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AccountClientsDeleteClientResponseObject); ok {
		return validResponse.VisitAccountClientsDeleteClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AccountClientsGetClient operation middleware
func (sh *strictHandler) AccountClientsGetClient(ctx echo.Context, id string) error {
	var request AccountClientsGetClientRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AccountClientsGetClient(ctx.Request().Context(), request.(AccountClientsGetClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AccountClientsGetClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AccountClientsGetClientResponseObject); ok {
		return validResponse.VisitAccountClientsGetClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AccountClientsUpdateClient operation middleware
func (sh *strictHandler) AccountClientsUpdateClient(ctx echo.Context, id string) error {
	var request AccountClientsUpdateClientRequestObject

	request.Id = id

	var body AccountClientsUpdateClientJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AccountClientsUpdateClient(ctx.Request().Context(), request.(AccountClientsUpdateClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AccountClientsUpdateClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AccountClientsUpdateClientResponseObject); ok {
		return validResponse.VisitAccountClientsUpdateClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ClientsInterfaceGetClient operation middleware
func (sh *strictHandler) ClientsInterfaceGetClient(ctx echo.Context, id string) error {
	var request ClientsInterfaceGetClientRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClientsInterfaceGetClient(ctx.Request().Context(), request.(ClientsInterfaceGetClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClientsInterfaceGetClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ClientsInterfaceGetClientResponseObject); ok {
		return validResponse.VisitClientsInterfaceGetClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthzCheck operation middleware
func (sh *strictHandler) HealthzCheck(ctx echo.Context) error {
	var request HealthzCheckRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthzCheck(ctx.Request().Context(), request.(HealthzCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthzCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthzCheckResponseObject); ok {
		return validResponse.VisitHealthzCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OAuthInterfaceAuthorize operation middleware
func (sh *strictHandler) OAuthInterfaceAuthorize(ctx echo.Context, params OAuthInterfaceAuthorizeParams) error {
	var request OAuthInterfaceAuthorizeRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OAuthInterfaceAuthorize(ctx.Request().Context(), request.(OAuthInterfaceAuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OAuthInterfaceAuthorize")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OAuthInterfaceAuthorizeResponseObject); ok {
		return validResponse.VisitOAuthInterfaceAuthorizeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OAuthInterfacePostAuthorize operation middleware
func (sh *strictHandler) OAuthInterfacePostAuthorize(ctx echo.Context) error {
	var request OAuthInterfacePostAuthorizeRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OAuthInterfacePostAuthorize(ctx.Request().Context(), request.(OAuthInterfacePostAuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OAuthInterfacePostAuthorize")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OAuthInterfacePostAuthorizeResponseObject); ok {
		return validResponse.VisitOAuthInterfacePostAuthorizeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OAuthInterfaceGetJwks operation middleware
func (sh *strictHandler) OAuthInterfaceGetJwks(ctx echo.Context) error {
	var request OAuthInterfaceGetJwksRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OAuthInterfaceGetJwks(ctx.Request().Context(), request.(OAuthInterfaceGetJwksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OAuthInterfaceGetJwks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OAuthInterfaceGetJwksResponseObject); ok {
		return validResponse.VisitOAuthInterfaceGetJwksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OAuthInterfaceGetToken operation middleware
func (sh *strictHandler) OAuthInterfaceGetToken(ctx echo.Context, params OAuthInterfaceGetTokenParams) error {
	var request OAuthInterfaceGetTokenRequestObject

	request.Params = params

	if form, err := ctx.FormParams(); err == nil {
		var body OAuthInterfaceGetTokenFormdataRequestBody
		if err := runtime.BindForm(&body, form, nil, nil); err != nil {
			return err
		}
		request.Body = &body
	} else {
		return err
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OAuthInterfaceGetToken(ctx.Request().Context(), request.(OAuthInterfaceGetTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OAuthInterfaceGetToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OAuthInterfaceGetTokenResponseObject); ok {
		return validResponse.VisitOAuthInterfaceGetTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SessionInterfaceLogout operation middleware
func (sh *strictHandler) SessionInterfaceLogout(ctx echo.Context) error {
	var request SessionInterfaceLogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SessionInterfaceLogout(ctx.Request().Context(), request.(SessionInterfaceLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionInterfaceLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SessionInterfaceLogoutResponseObject); ok {
		return validResponse.VisitSessionInterfaceLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SessionInterfaceMe operation middleware
func (sh *strictHandler) SessionInterfaceMe(ctx echo.Context) error {
	var request SessionInterfaceMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SessionInterfaceMe(ctx.Request().Context(), request.(SessionInterfaceMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionInterfaceMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SessionInterfaceMeResponseObject); ok {
		return validResponse.VisitSessionInterfaceMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SessionInterfaceLogin operation middleware
func (sh *strictHandler) SessionInterfaceLogin(ctx echo.Context) error {
	var request SessionInterfaceLoginRequestObject

	var body SessionInterfaceLoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SessionInterfaceLogin(ctx.Request().Context(), request.(SessionInterfaceLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionInterfaceLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SessionInterfaceLoginResponseObject); ok {
		return validResponse.VisitSessionInterfaceLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UserinfoGetUserinfo operation middleware
func (sh *strictHandler) UserinfoGetUserinfo(ctx echo.Context) error {
	var request UserinfoGetUserinfoRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UserinfoGetUserinfo(ctx.Request().Context(), request.(UserinfoGetUserinfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserinfoGetUserinfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UserinfoGetUserinfoResponseObject); ok {
		return validResponse.VisitUserinfoGetUserinfoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UsersInterfaceSignup operation middleware
func (sh *strictHandler) UsersInterfaceSignup(ctx echo.Context) error {
	var request UsersInterfaceSignupRequestObject

	var body UsersInterfaceSignupJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UsersInterfaceSignup(ctx.Request().Context(), request.(UsersInterfaceSignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UsersInterfaceSignup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UsersInterfaceSignupResponseObject); ok {
		return validResponse.VisitUsersInterfaceSignupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W/bOBL/VwjeAfui2Nk2OOD8luYO2e5ur0HS4h6KwKDFscVWJhV+JPEW/t8XJCVZ",
	"H5QlJ3aSTfclkSxyOB+/mSGH8x3HYpkJDlwrPPmOVZzAkrjH0zgWhuvRaZZJcUtSNfqdKV2+XYIblUmR",
	"gdTMv5Hiq31hGpbu4Z8S5niC/zHerDXOFxoX9PA6wnqVAZ5gIiVZ4fU6whJuDJNA8eRLhfR1OVLMvkKs",
	"7dSC2bOUWfKjMwlEg3+7hJs2p5wswf7PKSktGV9gtyZlEmI9NbIhRmvoVn7dAk1yw1mn/rXNOKNBXvYv",
	"T4QVxBJ0YGhDVEZxVMibz3mI4J8z+pexWYHaFo9xabZtqL8ws5TFuYnXUZdRVSwyeIxAzjI5SyW5bQKp",
	"3N3hv1La5YCbpSPEb0nK6LSkVfzgaFZIbhhrkQza1BOcblNAPwA3RIopIRmf3aO2uE0/5AovOQftHxsW",
	"ynXAhZ7OheE0aJMWkWAUfwiGgxYJCvLx1OhkZP8Iyf7oApolBsoizXBSjK3gj8QxKDWlwBlQN0qZLBNS",
	"g52rMsEVTN3aTazaGCVvQU5BSiFxhDUsMyGJZOlqaji5JSwlszQM6gbzl3DzwaSaXRCpd8X2ktxPycJB",
	"bC7kkmg8wYzrt29wuS7jGhYgG6BjHaisCt1ju5YYfu4nO3WL20VYaaIHOGTTAlUHrUmyzV+3MVkFvqDb",
	"bPVJfAN+RuIEzgTXUqS/AKFQwxwXR0oL2UulB6o9s88l4brJfAFtopng0yGiXEiyWJKHCxGOwnbhkL0X",
	"lukdINWQtB+4DeBU1os8Vw0K3UDJpQvtSn2s0HZAUEq4z5gENWV8oDcyWqHGdGo/v6fI/RYhNkcO1Yjx",
	"ODUUFPpJZMAZ/QkHbOMm7api/8epuLlPrgpbo16Ts0ePG/oViL0DIkEGAVZLBo/MsJ1pMsTzFSjFBB/9",
	"Lhasy0Ht5KmQ04wodSdkODXWCO22/Szp9sqSZ/sAI0GJhGlmeZveU7FYAK0bsS3HBwj6glE+bJA0/TjH",
	"ky/bEffZjl5fR5ib1CfFiZYGWlw3xHSLhGT7nK8egkfV7f51EnS7fQDGssD4XIyKh6CaOm2tzKyfAzuo",
	"a201uoSbK7bgJtsPxDYfp7Hgc2a1yATfHYxdhLol8WI0IWq9LQW+0InbjQIXZpHkJpmSVAKhq6lRUFsx",
	"NCHIjhuyJDpOAvD3h1YjmV5dWQh7rZ5m7DdY2eDm0MbxBMdCfGNQ4GTi8vAGcsRNsHK+I4rFxUznFfb7",
	"zP66GZ5onbnBLj62R/uw2RhuebXwq6aQU8/FLUjlLIiPR8ejY0va5g+SMTzBb91PVjk6cdKNiT9Hj2vF",
	"l4U/uFtwObW9p5Z+MaJWycGbzaOb+ub42O8JuM6jOcmylMWOzvir8tjyIaK3vNNfRHKaoKBiyTIPXPwp",
	"AZTvqlBCFFImjgEo0FHNxC58VY375drGKmWWSyJXeILPQSOSpmijGestQm1TzXuuQc5JDPmpFXunAaXf",
	"Cbran2JCp+N13UVtqF23jHNi/7X0JQExhbhAOXdIC6SAUzQXEumEqUKhEZoZjXQCKHF7SIWWZIVmgIyC",
	"uUlHyOroZEcI1KOYP1jtqgAbRuxezE6e1uTrC2TFQa49tR26wmDzJ0IUC5NSxIVGhlvVaMKpU1UBRmrA",
	"KjbfWCC14prc7wjKXFxEkA06BWlHo+3K4++Mrr3BU/Anrw7c/scNKAtTNkBIsgQNUjmWXNizQWMT9PLj",
	"WBVuUcWoTaVfPxMUT/YBxSEI2hUthFuozFkdJECRBCWMjGFHZHgTIsLLgFVHhT9Fbwnvflxe5LGBNn98",
	"bIQPlTWGl/g3Zc6t5bCC7FAr7DNBFGt3p4eaaqu3C4/IDw+puvVddAwuxA1JNT8/kzh016riDghBNqYT",
	"xOGudFM3YAbAUeyXR0QhYj+bVI/2mA8PEYSeImV5q+Raize2aUam/mxVcyMf70o3ejUJ64fGSpHESpxE",
	"Q5JVeSHxNDg4PnhgO2AEG/1g2yKXpCtwGpKhq3fJB4PU82X95lX5XrP+30Hy4EHS26+CaptMm0k0GDZz",
	"BJRVihcdOPsDZOMq+gFh8OCFiuDF+1+5UNERWC0EEyCpTv7oRN8v/vtZAvG3jkPlbge1zRbTkkR+fc+L",
	"IEYn4/Luv5Mnd2u1qdqV41v+APdZ6u455yRVEHn/uDEgVxsHaV5cd/vKg6/X19EwVup35kNdNhoqZ+0S",
	"fu/0i1aL/RN2DQh7IFS0X1RJ9d78PtOR4u3xm/Yql7kJ7VuE89l2WCri8gZouP7XTxNNA90/A2Pp4OaT",
	"FxZlT6stHuiyKPd27WPr4exCKF0Nad2bzqVJNcuI1GOL4iNKNBmejLe1Nb2YPePfXvD6vGCT6L/efVMD",
	"c/w56F/t6EfuTgmlzH4i6UXVgus91J9rW6xfrz7+D/0fZug3WKErqElddhENCQbnoD/lbT2hrb4Hf/1O",
	"u1T5YU6390d3d3dHLuAYmQKPBQW6a9gp29IGRZr9nUAabWO7mbkWa2ISJ3AU+/7C7QFnIEOBhkXLXuaa",
	"//ayQq2P8IkDX9lN+VrueyttIqHqlfdy5/bKt2dtK5LnHVyl2/tGMPwMOXeXkkbOZVe5tynUBzhk20m9",
	"Ce7AF4iFSTu3dAGDMn6gvpJWG+OP1FPSagZ9FWUaDxcXPUzes9i5USqaGs9BF4+H9LNgM+Uj3a3aRRdy",
	"t1IHpUbUWG36KYMe6NoVS//Luy8P44DNHs+X4X+17YoCfZQ3QL7Ew1Gzt/RVOHEVDZ6w37nXl7WoR1fu",
	"M46wkWneLqomY1cJHWWMr/59cjyKxXJMMja+/Rmvr9d/BgAA//84lP3oxjsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
