// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"auth/internal/api"
	"auth/internal/domain"
	"auth/internal/domain/oauth"
	"auth/internal/infrastructure"
	"auth/internal/infrastructure/gateway"
	"auth/internal/middleware"
	"auth/internal/usecase"
)

// Injectors from wire.go:

func NewServer() *api.Server {
	db := infrastructure.GetDB()
	iUserRepo := gateway.NewUserRepo(db)
	userService := domain.NewUserService(iUserRepo)
	userUsecase := usecase.NewAuthUsecase(userService, iUserRepo)
	iClientRepo := gateway.NewClientRepo(db)
	iApprovalRepo := gateway.NewApprovalRepo(db)
	iAuthCodeRepo := gateway.NewAuthCodeRepo(db)
	requestService := oauth.NewRequestService(iClientRepo, iApprovalRepo, iAuthCodeRepo)
	authCodeService := oauth.NewAuthCodeService(iAuthCodeRepo)
	config := oauth.NewConfig()
	jwKsService := oauth.NewJWKsService(config)
	approvalService := oauth.NewApprovalService(iApprovalRepo)
	tokenService := oauth.NewTokenService(config, iUserRepo)
	oAuthUsecase := usecase.NewOAuthUsecase(requestService, authCodeService, jwKsService, approvalService, iApprovalRepo, tokenService, iClientRepo)
	iClientUsecase := usecase.NewClientUsecase(iClientRepo)
	server := api.NewServer(userUsecase, oAuthUsecase, iClientUsecase)
	return server
}

func NewAuthMiddleware() *middleware.AuthMiddleware {
	db := infrastructure.GetDB()
	iClientRepo := gateway.NewClientRepo(db)
	authMiddleware := middleware.NewAuthMiddleware(iClientRepo)
	return authMiddleware
}
