// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameApprovalScope = "approval_scopes"

// ApprovalScope mapped from table <approval_scopes>
type ApprovalScope struct {
	ScopeID    int32 `gorm:"column:scope_id;primaryKey" json:"scope_id"`
	ApprovalID int64 `gorm:"column:approval_id;primaryKey" json:"approval_id"`
}

// TableName ApprovalScope's table name
func (*ApprovalScope) TableName() string {
	return TableNameApprovalScope
}
