// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClient = "clients"

// Client mapped from table <clients>
type Client struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	EncryptedSecret string    `gorm:"column:encrypted_secret;not null" json:"encrypted_secret"`
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Client's table name
func (*Client) TableName() string {
	return TableNameClient
}
