// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRedirectURI = "redirect_uris"

// RedirectURI mapped from table <redirect_uris>
type RedirectURI struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClientID  string    `gorm:"column:client_id;not null" json:"client_id"`
	URI       string    `gorm:"column:uri;not null" json:"uri"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName RedirectURI's table name
func (*RedirectURI) TableName() string {
	return TableNameRedirectURI
}
