name: Build App for Production
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  prd-build-backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-backend:1.0.${{ github.run_number }}
          path: "."
  prd-build-frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-frontend:1.0.${{ github.run_number }}
          path: "./frontend"
          build-args: |
            - NEXT_PUBLIC_BACKEND_URL=http://auth.default.svc.cluster.local:8080/api/v1