name: Build App for Production
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.frontend.outputs.frontend }}
      spec: ${{ steps.spec.outputs.spec }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - "frontend/**"
              - ".github/workflows/prd-deploy.yaml"
            spec:
              - "spec/**"
              - ".github/workflows/prd-deploy.yaml"
  prd-build-backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-backend:1.0.${{ github.run_number }}
          path: "."
  prd-build-frontend:
    runs-on: ubuntu-latest
    environment: production
    needs: filter
    if: needs.filter.outputs.frontend == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-frontend:1.0.${{ github.run_number }}
          path: "./frontend"
          build-args: |
            - NEXT_PUBLIC_BACKEND_URL=https://auth.piny940.com/api/v1
