name: Build App for Staging
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      spec: ${{ steps.filter.outputs.spec }}
      example: ${{ steps.filter.outputs.example }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - "frontend/**"
              - ".github/workflows/stg-deploy.yaml"
            spec:
              - "spec/**"
              - ".github/workflows/stg-deploy.yaml"
            example:
              - "example/**"
              - ".github/workflows/stg-deploy.yaml"
  stg-build-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment: staging # 管理者の承認を必要とする
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-backend:stg-${{ github.sha }}-${{ github.run_number }}
          path: "."
          cache-registry: ghcr.io/${{ github.repository }}-backend:buildcache
  stg-build-backend-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-backend:stg-${{ github.sha }}-${{ github.run_number }}
          path: "."
          cache-registry: ghcr.io/${{ github.repository }}-backend:buildcache

  stg-build-frontend:
    runs-on: ubuntu-latest
    needs: filter
    if: github.event_name == 'pull_request' && needs.filter.outputs.frontend == 'true'
    environment: staging # 管理者の承認を必要とする
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-frontend:stg-${{ github.sha }}-${{ github.run_number }}
          path: "./frontend"
          build-args: |
            NEXT_PUBLIC_API_URL=https://stg-auth.piny940.com/api/v1
          cache-registry: ghcr.io/${{ github.repository }}-frontend:buildcache
  stg-build-frontend-main:
    runs-on: ubuntu-latest
    needs: filter
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.filter.outputs.frontend == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-frontend:stg-${{ github.sha }}-${{ github.run_number }}
          path: "./frontend"
          build-args: |
            NEXT_PUBLIC_API_URL=https://stg-auth.piny940.com/api/v1
          cache-registry: ghcr.io/${{ github.repository }}-frontend:buildcache

  stg-build-example:
    runs-on: ubuntu-latest
    needs: filter
    if: github.event_name == 'pull_request' && needs.filter.outputs.example == 'true'
    environment: staging # 管理者の承認を必要とする
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-example:stg-${{ github.sha }}-${{ github.run_number }}
          path: "./example"
          cache-registry: ghcr.io/${{ github.repository }}-example:buildcache
  stg-build-example-main:
    runs-on: ubuntu-latest
    needs: filter
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.filter.outputs.example == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: ghcr.io/${{ github.repository }}-example:stg-${{ github.sha }}-${{ github.run_number }}
          path: "./example"
          cache-registry: ghcr.io/${{ github.repository }}-example:buildcache

  build-doc:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.spec == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION}}
          package_json_file: "spec/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "spec/package.json"
      - name: Build doc
        run: cd spec && pnpm run export
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            page deploy --project-name=auth-doc spec/out
